[package]
name = "vse2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22.0"
glow = "0.11.2"
sdl2 = "0.35.2"
